export const actionTypes = {
  FETCH_WEAPONS: 'FETCH_WEAPONS',
  FETCH_MODES: 'FETCH_MODES',
  PLAY: 'PLAY',
  RESULT: 'RESULT',
  RESTART: 'RESTART',
  RESET: 'RESET',
  UPDATE_MODE: 'UPDATE_MODE',
  CHANGE_MODE: 'CHANGE_MODE',
};
